version: "3"
services:
        nginx-frontend:
                image: nginxresizeimage
                container_name: nginx_frontend
                ports:
                        - "80:80"
                        - "443:443"
                        - "9001:9001"
                        - "9002:9002"
                volumes:
                        - /var/run/docker.sock:/tmp/docker.sock:ro

